# We start Air at repo root
root = "."

# Keep temp files inside the service
tmp_dir = "gateway-service/tmp"

[build]
cmd = "cd gateway-service && go build -o tmp/server ./cmd"
entrypoint = "gateway-service/tmp/server"

include_ext = ["go"]
exclude_dir = ["gateway-service/tmp", "vendor"]

[run]
cmd = "gateway-service/tmp/server"

