# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app ./cmd"
  bin = "./tmp/app"
  delay = 200
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", ".git"]
  stop_on_error = true

[log]
  time = true

